package com.fleetmatch.notification.entity;

public enum NotificationType {
    NEW_OFFER,
    OFFER_ACCEPTED,
    OFFER_REJECTED,
    FLEET_CONFIRMED,
    NEW_MESSAGE,
    LOAD_STARTED,
    LOAD_DELIVERED,
    LOAD_CANCELLED,
    COMPANY_APPROVED,
    COMPANY_REJECTED,
    COMPANY_SUSPENDED,
    COMPANY_REACTIVATED,
    SUBSCRIPTION_ASSIGNED,
    SUBSCRIPTION_EXPIRING
}
