package com.fleetmatch.audit.entity;

public enum AuditAction {
    USER_REGISTERED,
    EMAIL_VERIFIED,
    PHONE_VERIFIED,
    EMAIL_CHANGED,
    PHONE_CHANGED,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    COMPANY_UPDATED,
    COMPANY_APPROVED,
    COMPANY_REJECTED,
    SUBSCRIPTION_ASSIGNED,
    SUBSCRIPTION_CHANGED,
    LOAD_CREATED,
    LOAD_UPDATED,
    LOAD_CANCELLED,
    OFFER_SUBMITTED,
    OFFER_ACCEPTED,
    OFFER_REJECTED,
    CONVERSATION_CREATED,
    LOAD_STARTED,
    LOAD_DELIVERED
}
