ALTER TABLE loads
    ADD COLUMN pickup_date DATE NOT NULL DEFAULT CURRENT_DATE,
ADD COLUMN delivery_date DATE,
ADD COLUMN miles INTEGER,
ADD COLUMN commodity VARCHAR(255),
ADD COLUMN reference_number VARCHAR(255);